"""
Shared branding for official PDF & Excel documents.

Every official document generated by the system uses:
  - A common letterhead: institute logo + name, document title, department,
    and relevant administrative data.
  - Light (visible) column headers — never dark fills.
  - A sign-off block: the officer in charge (e.g. HOD) followed by the
    Chief Principal, each with Name / Sign / Date, plus a stamp area.
"""

import os

INSTITUTE = "THIKA TECHNICAL TRAINING INSTITUTE"
INSTITUTE_TAGLINE = "Academic Management System — Official Document"

_BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOGO_PATH = os.path.join(_BASE_DIR, "static", "assets", "THIKATTILOGO.jpg")
COAT_PATH = os.path.join(_BASE_DIR, "static", "assets", "KENYACOATOFARMS.png")

# Light, visible header palette (dark text on light fill)
HEADER_FILL_HEX = "DCE6F4"      # light steel blue
HEADER_TEXT_HEX = "0F2744"      # navy text
HEADER_BORDER_HEX = "B7C4D8"
ACCENT_HEX = "B45309"           # institutional gold for document titles
SUBTLE_HEX = "64748B"

CHIEF_PRINCIPAL_TITLE = "Chief Principal"


# ══════════════════════════════════════════════════════════════════════════
# Excel (openpyxl)
# ══════════════════════════════════════════════════════════════════════════

def excel_add_logo(ws, anchor="A1", height=58):
    """Embed the institute logo at the given cell anchor. Safe if missing."""
    if not os.path.exists(LOGO_PATH):
        return
    try:
        from openpyxl.drawing.image import Image as XLImage
        img = XLImage(LOGO_PATH)
        ratio = img.width / img.height if img.height else 1
        img.height = height
        img.width = int(height * ratio)
        ws.add_image(img, anchor)
    except Exception:
        pass


def excel_letterhead(ws, doc_name, total_cols, dept_name="", meta_lines=(),
                     start_row=1, with_logo=True):
    """
    Write the common letterhead. Returns the next free row number.
    Rows: institute name, tagline, document name, department, meta lines.
    """
    from openpyxl.styles import Font, Alignment
    from openpyxl.utils import get_column_letter

    last = get_column_letter(max(total_cols, 4))
    center = Alignment(horizontal="center", vertical="center")
    r = start_row

    if with_logo:
        excel_add_logo(ws, anchor=f"A{r}")

    ws.merge_cells(f"A{r}:{last}{r}")
    c = ws.cell(row=r, column=1, value=INSTITUTE)
    c.font = Font(bold=True, size=15, color=HEADER_TEXT_HEX)
    c.alignment = center
    ws.row_dimensions[r].height = 24
    r += 1

    ws.merge_cells(f"A{r}:{last}{r}")
    c = ws.cell(row=r, column=1, value=INSTITUTE_TAGLINE)
    c.font = Font(size=9, italic=True, color=SUBTLE_HEX)
    c.alignment = center
    r += 1

    ws.merge_cells(f"A{r}:{last}{r}")
    c = ws.cell(row=r, column=1, value=str(doc_name).upper())
    c.font = Font(bold=True, size=12, color=ACCENT_HEX)
    c.alignment = center
    ws.row_dimensions[r].height = 20
    r += 1

    if dept_name:
        ws.merge_cells(f"A{r}:{last}{r}")
        c = ws.cell(row=r, column=1, value=f"Department: {dept_name}")
        c.font = Font(bold=True, size=10, color="334155")
        c.alignment = center
        r += 1

    for line in meta_lines:
        if not line:
            continue
        ws.merge_cells(f"A{r}:{last}{r}")
        c = ws.cell(row=r, column=1, value=line)
        c.font = Font(size=9, color=SUBTLE_HEX)
        c.alignment = center
        r += 1

    return r + 1  # one blank spacer row


def excel_header_styles():
    """Light, visible column-header styles (dark text on light fill)."""
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    thin = Side(style="thin", color=HEADER_BORDER_HEX)
    return {
        "fill": PatternFill("solid", fgColor=HEADER_FILL_HEX),
        "font": Font(bold=True, color=HEADER_TEXT_HEX, size=10),
        "alignment": Alignment(horizontal="center", vertical="center", wrap_text=True),
        "border": Border(left=thin, right=thin, top=thin, bottom=thin),
    }


def style_header_row(ws, row, total_cols):
    """Apply the light header style to every cell in a header row."""
    st = excel_header_styles()
    for col in range(1, total_cols + 1):
        cell = ws.cell(row=row, column=col)
        cell.fill = st["fill"]
        cell.font = st["font"]
        cell.alignment = st["alignment"]
        cell.border = st["border"]


def excel_signature_block(ws, start_row, officer_title="Head of Department",
                          officer_name="", extra_officers=()):
    """
    Official sign-off: officer in charge, any extra officers, then the
    Chief Principal — each with Name / Sign / Date — plus a stamp area.
    Returns the next free row.
    """
    from openpyxl.styles import Font

    titles = [(officer_title, officer_name)]
    titles += [(t, "") for t in extra_officers]
    titles.append((CHIEF_PRINCIPAL_TITLE, ""))

    r = start_row + 1
    ws.cell(row=r, column=1, value="OFFICIAL SIGN-OFF").font = Font(
        bold=True, size=11, color=HEADER_TEXT_HEX)
    r += 2
    for title, name in titles:
        label = f"{title}:"
        ws.cell(row=r, column=1, value=label).font = Font(bold=True, size=10)
        name_part = name if name else "_______________________________"
        ws.cell(
            row=r + 1, column=1,
            value=f"Name: {name_part}    Sign: ______________________    Date: ________________",
        ).font = Font(size=10)
        r += 3

    ws.cell(row=r, column=1, value="Official Stamp:").font = Font(bold=True, size=10)
    ws.cell(row=r + 1, column=1, value="(Affix official institute stamp here)").font = Font(
        size=9, italic=True, color=SUBTLE_HEX)
    return r + 4


# ══════════════════════════════════════════════════════════════════════════
# PDF (ReportLab)
# ══════════════════════════════════════════════════════════════════════════

def pdf_letterhead(doc_name, avail_width, dept_name="", meta_lines=()):
    """
    Return a list of ReportLab flowables forming the common letterhead:
    coat of arms + institute name/document title/department + institute logo.
    `avail_width` is the usable page width in points.
    """
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        HRFlowable, Image as RLImage, Paragraph, Spacer, Table, TableStyle,
    )

    styles = getSampleStyleSheet()
    navy = colors.HexColor("#0F2744")
    gold = colors.HexColor("#B45309")

    title_s = ParagraphStyle(
        "lh_t", parent=styles["Heading1"], fontSize=14, textColor=navy,
        alignment=TA_CENTER, spaceAfter=1, fontName="Helvetica-Bold", leading=17,
    )
    tag_s = ParagraphStyle(
        "lh_tag", parent=styles["Normal"], fontSize=7.5,
        textColor=colors.HexColor("#64748B"), alignment=TA_CENTER, spaceAfter=2,
    )
    doc_s = ParagraphStyle(
        "lh_d", parent=styles["Normal"], fontSize=11, textColor=gold,
        alignment=TA_CENTER, spaceAfter=2, fontName="Helvetica-Bold",
    )
    dept_s = ParagraphStyle(
        "lh_dep", parent=styles["Normal"], fontSize=9,
        textColor=colors.HexColor("#334155"), alignment=TA_CENTER,
        spaceAfter=1, fontName="Helvetica-Bold",
    )
    meta_s = ParagraphStyle(
        "lh_m", parent=styles["Normal"], fontSize=8,
        textColor=colors.HexColor("#475569"), alignment=TA_CENTER, spaceAfter=1,
    )

    center = [Paragraph(INSTITUTE, title_s), Paragraph(INSTITUTE_TAGLINE, tag_s),
              Paragraph(str(doc_name).upper(), doc_s)]
    if dept_name:
        center.append(Paragraph(f"Department: {dept_name}", dept_s))
    for line in meta_lines:
        if line:
            center.append(Paragraph(line, meta_s))

    side = 24 * mm

    def _img(path):
        if os.path.exists(path):
            try:
                return RLImage(path, width=19 * mm, height=19 * mm)
            except Exception:
                return ""
        return ""

    row = [[_img(COAT_PATH), center, _img(LOGO_PATH)]]
    t = Table(row, colWidths=[side, avail_width - 2 * side, side])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (0, 0), "CENTER"),
        ("ALIGN", (2, 0), (2, 0), "CENTER"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))
    return [t, Spacer(1, 3),
            HRFlowable(width="100%", thickness=1.2, color=navy, spaceAfter=8)]


def pdf_header_style_cmds(header_row=0):
    """TableStyle commands for a light, visible header row (no dark fill)."""
    from reportlab.lib import colors
    return [
        ("BACKGROUND", (0, header_row), (-1, header_row), colors.HexColor("#DCE6F4")),
        ("TEXTCOLOR", (0, header_row), (-1, header_row), colors.HexColor("#0F2744")),
        ("FONTNAME", (0, header_row), (-1, header_row), "Helvetica-Bold"),
        ("LINEBELOW", (0, header_row), (-1, header_row), 0.8, colors.HexColor("#0F2744")),
    ]


def pdf_signature_block(avail_width, officer_title="Head of Department",
                        officer_name="", extra_officers=()):
    """
    Return flowables for the official sign-off: officer in charge, any extra
    officers, then the Chief Principal — each with Name / Sign / Date — plus
    a stamp box.
    """
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle

    styles = getSampleStyleSheet()
    lbl_s = ParagraphStyle(
        "sig_l", parent=styles["Normal"], fontSize=8.5,
        fontName="Helvetica-Bold", textColor=colors.HexColor("#0F2744"),
        spaceAfter=2,
    )
    line_s = ParagraphStyle(
        "sig_ln", parent=styles["Normal"], fontSize=8,
        textColor=colors.HexColor("#334155"), leading=14,
    )
    stamp_s = ParagraphStyle(
        "sig_st", parent=styles["Normal"], fontSize=7.5,
        textColor=colors.HexColor("#64748B"), alignment=1,
    )

    officers = [(officer_title, officer_name)]
    officers += [(t, "") for t in extra_officers]
    officers.append((CHIEF_PRINCIPAL_TITLE, ""))

    cells = []
    for title, name in officers:
        name_part = name if name else "___________________________"
        cells.append([
            Paragraph(title.upper(), lbl_s),
            Paragraph(f"Name: {name_part}", line_s),
            Paragraph("Sign: ___________________________", line_s),
            Paragraph("Date: ___________________________", line_s),
        ])
    # Stamp box as final column
    cells.append([
        Paragraph("OFFICIAL STAMP", lbl_s),
        Spacer(1, 26),
        Paragraph("(Affix institute stamp here)", stamp_s),
    ])

    ncols = len(cells)
    gap = 4 * mm
    col_w = (avail_width - gap * (ncols - 1)) / ncols
    data = [cells]
    widths = [col_w] * ncols

    t = Table(data, colWidths=widths)
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOX", (-1, 0), (-1, 0), 0.8, colors.HexColor("#94A3B8")),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return [Spacer(1, 14), t]
